### ISSUE TITLE
DRM doesn't seem to work

### ISSUE THREAD

**Issue by Thelucyinside** [itsxrp/android_device_realme_lunaa#1]
Love your ROM, thank you for maintaining it!
I had some issues with DRM related content, which I hadn't on the stock ROM.

**Comment by itsxrp** [comment]
Latest a15 build is ready and netflix is fixed
You can try it.

**Comment by itsxrp** [comment]
Latest a15 build is ready and netflix is fixed
You can try it.

**Comment by itsxrp** [comment]
Latest a15 build is ready and netflix is fixed
You can try it.

**Comment by Thelucyinside** [comment]
Im really sorry, but I cant find the build. Where is it located?
